site_name: XLMA Python

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Home: index.md
  - API Reference:
      - coords:
        - api/coords/index.md
        - api/coords/transforms.md
      - xarray:
        - api/xarray/index.md
      - lmalib:
        - api/lmalib/flash.md

