site_name: XLMA Python

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Home: index.md
  - API Reference:
      - coords:
        - api/coords/index.md
        - api/coords/transforms.md
      - xarray:
        - api/xarray/index.md
      #     - GeographicSystem: api/coords/GeographicSystem.md
      #     - MapProjection: api/coords/MapProjection.md
      #     - PixelGrid: api/coords/PixelGrid.md
      #     - GeostationaryFixedGridSystem: api/coords/GeostationaryFixedGridSystem.md
      #     - RadarCoordinateSystem: api/coords/RadarCoordinateSystem.md
      #     - TangentPlaneCartesianSystem: api/coords/TangentPlaneCartesianSystem.md
