site_name: XLMA Python
repo_url: https://github.com/deeplycloudy/xlma-python


theme:
  name: material
  logo: xlma_logo_big_big_ltg.svg
  favicon: xlma_logo_big_big_ltg.svg
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Home: index.md
  - API Reference:
      - coords:
        - api/coords/index.md
        - api/coords/transforms.md
      - xarray:
        - api/xarray/index.md
      - lmalib:
        - api/lmalib/flash.md
        - api/lmalib/cf_netcdf.md

